### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by tipouic** [cody82/LiPoSensor#1]
Where can you find the libraries you use ?
Can you add them to this project ?

**Comment by cody82** [comment]
I added the Frsky Smart Port library in commit 8952f660ee2476a96c9a7a02b877e5d1de86f40d.
The FrskyD library might be this one: https://github.com/jcheger/arduino-frskyd, but I dont remember.
I will check and add it then.

**Comment by cody82** [comment]
Also added the other repo.

**Comment by tipouic** [comment]
Thank you very much
